version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 853485304571.dkr.ecr.us-east-2.amazonaws.com
      - REPOSITORY_URI=853485304571.dkr.ecr.us-east-2.amazonaws.com/nexogic-patient-service
      - REPO_NAME=nexogic-patient-service
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - mvn -v
      - echo Build started on `date`
      - echo Building the Docker image...
      -  mvn clean install -Ddocker.image.prefix=$REPO_NAME dockerfile:build
      - docker tag nexogic/nexogic-patient-service/nexogic-patient:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"Nexogic-Patient-Service","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json